# This file gives Netlify explicit instructions and overrides the UI settings.

[build]
  # This tells Netlify that the root of your repository is where the site lives.
  # Setting base to "" (an empty string) is the correct way to do this.
  base = ""
  
  # This confirms that the folder to publish is the main root folder.
  publish = "/"

# This gives explicit instructions for our RSVP form.
[[forms]]
  # The 'name' must EXACTLY match the name in your form tag.
  name = "rsvp-final"
  
  # We will point back to the full filename to be as explicit as possible.
  action = "/thank-you.html"
