Object.assign(translations.en, {
    "lovestory_page_title": "Our Story",
    "lovestory_intro": "🏀 Basketball has always been our shared passion. Maybe we are not the best players, but the game has brought so much into our lives: frustration, joy, friendship, and love. 'Love and Basketball' is our motto for the day, as it was through basketball that we met each other.",
    "lovestory_howwemet_title": "How We Met",
    "lovestory_howwemet_text": "We both started sharing a city in 2019, and once Juanma began training in Blankenese, we started sharing training facilities. The boys' and girls' teams shared common space and played some friendly pick-up games once in a while. Thanks to this great environment, we all found ourselves sharing a dinner at an Italian restaurant in Schanze 🍝. It was by chance that we both ended up there, but it was no chance that we ended up talking the whole night.",
    "lovestory_first_dates_title": "Pandemic First Dates",
    "lovestory_first_dates_text": "Our first dates were during the pandemic, which meant we had to get imaginative with what to do. The highlights were:",
    "lovestory_highlight_1": "Drinking a beer in a public street with our masks on.",
    "lovestory_highlight_2": "Going grocery shopping together at our macro-shop where not so many people shopped, so we could wander the aisles and get nice things to cook at home.",
    "lovestory_highlight_3": "Endlessly walking the Volkspark with Rollo 🐕 and having date-nights at both our former living places.",
    "lovestory_continuation_text": "All of that condensed time brought us together without any filters, really getting to know each other far from the idealistic plans of fancy restaurants. We met friends, we met family, expanded our circles, got to know our music tastes (somehow slightly compatible) and our film tastes (completely incompatible). Jessica learnt Spanish and how to differentiate the good jamón from the bad one. Some trips to Spain and Denmark later we decided to move together into our shoe-box-sized apartment in Kühnehöfe. By the time that we got used to sharing the small space with Rollo, we welcomed Nuria into our lives and now we live with the best fit for us, creating memories in our bi-cultural space.",
    "lovestory_why_wedding_title": "So, Why a Wedding?",
    "lovestory_why_wedding_text": "We, very unromantically, decided that it was best for us to get married. Romance started when Juanma proposed on Jessica's birthday, in Cafe Paris, with a ring-project-box, kind words, champagne and a wedding request in Valladolid... who can say 'no' to that? ❤️ Living far from our hometowns (Detmold and Valladolid) definitely has the perk of keeping friendships alive from a distance. We decided that this was our best opportunity to bring together all those who we value into one event, to celebrate love and basketball, our cultures, joy, and to party!"
});
Object.assign(translations.es, {
    "lovestory_page_title": "Nuestra Historia",
    "lovestory_intro": "🏀 El baloncesto siempre ha sido nuestra pasión compartida. Quizás no seamos los mejores jugadores, pero este deporte nos ha dado mucho en la vida: frustración, alegría, amistad y amor. 'Amor y Baloncesto' es nuestro lema para el gran día, ya que fue a través del baloncesto como nos conocimos.",
    "lovestory_howwemet_title": "Cómo Nos Conocimos",
    "lovestory_howwemet_text": "Ambos empezamos a compartir ciudad en 2019, y una vez que Juanma comenzó a entrenar en Blankenese, empezamos a compartir instalaciones. Los equipos masculino y femenino compartían espacios y jugaban pachangas amistosas de vez en cuando. Gracias a este buen ambiente, acabamos todos cenando en un restaurante italiano en Schanze 🍝. Fue una casualidad que ambos acabáramos allí, pero no fue casualidad que termináramos hablando toda la noche.",
    "lovestory_first_dates_title": "Primeras Citas en Pandemia",
    "lovestory_first_dates_text": "Nuestras primeras citas fueron durante la pandemia, lo que significó que tuvimos que usar la imaginación. Nuestros mejores recuerdos incluyen:",
    "lovestory_highlight_1": "Tomar una cerveza en la calle con nuestras mascarillas puestas.",
    "lovestory_highlight_2": "Ir de compras juntos a nuestro supermercado gigante donde no había mucha gente, para poder pasear por los pasillos y encontrar cosas ricas para cocinar en casa.",
    "lovestory_highlight_3": "Pasear sin fin por el Volkspark con Rollo 🐕 y tener citas nocturnas en nuestros antiguos pisos.",
    "lovestory_continuation_text": "Todo ese tiempo condensado nos unió sin filtros, permitiéndonos conocernos de verdad, lejos de los planes idealistas de restaurantes elegantes. Conocimos a amigos, a familia, ampliamos nuestros círculos, descubrimos nuestros gustos musicales (ligeramente compatibles) y cinematográficos (completamente incompatibles). Jessica aprendió español y a diferenciar el jamón bueno del malo. Unos viajes a España y Dinamarca después, decidimos mudarnos juntos a nuestro apartamento tamaño caja de zapatos en Kühnehöfe. Cuando nos acostumbramos a compartir el pequeño espacio con Rolli, dimos la bienvenida a Nuria a nuestras vidas y ahora vivimos como mejor nos encaja, creando recuerdos en nuestro espacio bicultural.",
    "lovestory_why_wedding_title": "¿Y por qué una Boda?",
    "lovestory_why_wedding_text": "Nosotros, de una forma muy poco romántica, decidimos que lo mejor para nosotros era casarnos. El romanticismo comenzó cuando Juanma se declaró en el cumpleaños de Jessica, en el Café Paris, con una caja-proyector de anillo, palabras bonitas, champán y una petición de boda en Valladolid... ¿quién puede decir 'no' a eso? ❤️ Vivir lejos de nuestras ciudades natales (Detmold y Valladolid) tiene la ventaja de mantener vivas las amistades a distancia. Decidimos que era nuestra mejor oportunidad para reunir a todos los que valoramos en un solo evento, para celebrar el amor y el baloncesto, nuestras culturas, la alegría y la fiesta."
});
Object.assign(translations.de, {
    "lovestory_page_title": "Unsere Geschichte",
    "lovestory_intro": "🏀 Basketball war schon immer unsere gemeinsame Leidenschaft. Vielleicht sind wir nicht die besten Spieler, aber das Spiel hat uns so viel in unserem Leben gegeben: Frustration, Freude, Freundschaft und Liebe. 'Love and Basketball' ist unser Motto für diesen Tag, denn durch Basketball haben wir uns kennengelernt.",
    "lovestory_howwemet_title": "Wie wir uns trafen",
    "lovestory_howwemet_text": "Wir begannen beide 2019, in derselben Stadt zu leben, und als Juanma anfing, in Blankenese zu trainieren, teilten wir uns die Trainingseinrichtungen. Die Herren- und Damenmannschaften teilten sich den Gemeinschaftsraum und spielten ab und zu ein paar freundschaftliche Pick-up-Spiele. Dank dieser großartigen Atmosphäre fanden wir uns alle bei einem Abendessen in einem italienischen Restaurant in der Schanze 🍝 wieder. Es war Zufall, dass wir beide dort landeten, aber es war kein Zufall, dass wir die ganze Nacht miteinander redeten.",
    "lovestory_first_dates_title": "Erste Dates während der Pandemie",
    "lovestory_first_dates_text": "Unsere ersten Dates fanden während der Pandemie statt, was bedeutete, dass wir einfallsreich sein mussten. Unsere schönsten Highlights sind:",
    "lovestory_highlight_1": "Ein Bier auf der Straße mit unseren Masken zu trinken.",
    "lovestory_highlight_2": "Gemeinsam in unserem riesigen Supermarkt einkaufen, wo nicht so viele Leute waren, damit wir durch die Gänge schlendern und schöne Dinge zum Kochen zu Hause finden konnten.",
    "lovestory_highlight_3": "Endlose Spaziergänge durch den Volkspark mit Rollo 🐕 und Verabredungen in unseren beiden ehemaligen Wohnungen.",
    "lovestory_continuation_text": "All diese komprimierte Zeit hat uns ohne Filter zusammengebracht und uns ermöglicht, uns wirklich kennenzulernen, weit entfernt von den idealistischen Plänen schicker Restaurants. Wir lernten Freunde kennen, trafen Familie, erweiterten unsere Kreise, lernten unsere Musikgeschmäcker (irgendwie leicht kompatibel) und unsere Filmgeschmäcker (völlig inkompatibel) kennen. Jessica lernte Spanisch und wie man den guten vom schlechten Jamón unterscheidet. Einige Reisen nach Spanien und Dänemark später beschlossen wir, in unsere schuhschachtelgroße Wohnung in den Kühnehöfen zusammenzuziehen. Als wir uns daran gewöhnt hatten, den kleinen Raum mit Rolli zu teilen, begrüßten wir Nuria in unserem Leben und leben nun, wie es für uns am besten passt, und schaffen Erinnerungen in unserem bikulturellen Raum.",
    "lovestory_why_wedding_title": "Also, warum eine Hochzeit?",
    "lovestory_why_wedding_text": "Wir entschieden sehr unromantisch, dass es das Beste für uns sei zu heiraten. Die Romantik begann, als Juanma an Jessicas Geburtstag im Café Paris mit einer Ring-Projektor-Box, freundlichen Worten, Champagner und einem Hochzeitsantrag in Valladolid um ihre Hand anhielt... wer kann dazu schon 'nein' sagen? ❤️ Weit weg von unseren Heimatstädten (Detmold und Valladolid) zu leben, hat definitiv den Vorteil, Freundschaften aus der Ferne am Leben zu erhalten. Wir entschieden, dass dies unsere beste Gelegenheit war, all jene, die wir schätzen, zu einem Ereignis zusammenzubringen, um die Liebe und den Basketball, unsere Kulturen, die Freude und das Feiern zu zelebrieren."
});
