Object.assign(translations.en, {
    "lovestory_page_title": "Our Story",
    "lovestory_intro": "🏀 Basketball has always been our shared passion. Maybe we are not the best players, but the game has brought so much into our lives: frustration, joy, friendship, and love. 'Love and Basketball' is our motto for the day, as it was through basketball that we met each other.",
    "lovestory_howwemet_title": "How We Met",
    "lovestory_howwemet_text": "We both started sharing a city in 2019, and once Juanma began training in Blankenese, we started sharing training facilities. Friendly pick-up games between the men's and women's teams led to a group dinner at an Italian restaurant in Schanze 🍝. It was by chance we both ended up there, but it was no chance that we ended up talking the whole night.",
    "lovestory_first_dates_title": "Pandemic First Dates",
    "lovestory_first_dates_text": "Our first dates were during the pandemic, which meant we had to get imaginative with what to do. The highlights were: Drinking a beer on a public street with our masks on, going grocery shopping together at our macro-shop where not so many people shopped, so we could wander the aisles and get nice things to cook at home, and endlessly walking the Volkspark with Rollo 🐕 and having date-nights at both our former living places.",
    "lovestory_building_life_title": "Building Our World Together",
    "lovestory_building_life_text": "That condensed time together, free from the distractions of fancy restaurants, allowed us to build something real. We met friends, we met family, expanded our circles and our hearts. We debated our music tastes (somehow slightly compatible 🎶) and our film tastes (completely incompatible 🎬). Jessica learnt Spanish and how to differentiate the good jamón from the bad one. Some trips to Spain and Denmark later, we decided to move together into our shoe-box-sized apartment in Kühnehöfe. By the time we got used to sharing that tiny space with Rollo, we welcomed Nuria into our lives, and now we live creating new memories every day in the beautiful, bi-cultural space that is our family.",
    "lovestory_proposal_title": "The Proposal & Civil Ceremony",
    "lovestory_proposal_text": "The decision to get married began, without a proposal, as a mutual agreement. The romantic part came as a big surprise for Jessica on her birthday in 2023 at the beautiful Café Paris in Hamburg. During a 'Breakfast for Two' and a glass of Crémant, Juanma proposed and set the date for the civil ceremony to November 28th of the same year - his birthday. So, in November 2023, we got married at the Elmshorn registry office, just the two of us with Nuria and Rollo.",
    "lovestory_why_wedding_title": "So, Why a Big Wedding Celebration?",
    "lovestory_why_wedding_text": "For us, living far from our hometowns of Detmold and Valladolid, we see this celebration as our best opportunity to bring all of you, the people we value most, together in one place. It's a chance to celebrate love, basketball, our cultures, joy, and to party!",
    "lovestory_gallery_title": "A Few of Our Favourite Moments"
});
Object.assign(translations.es, {
    "lovestory_page_title": "Nuestra Historia",
    "lovestory_intro": "🏀 El baloncesto siempre ha sido nuestra pasión compartida. Quizás no seamos los mejores jugadores, pero este deporte nos ha dado mucho en la vida: frustración, alegría, amistad y amor. 'Amor y Baloncesto' es nuestro lema para el gran día, ya que fue a través del baloncesto como nos conocimos.",
    "lovestory_howwemet_title": "Cómo Nos Conocimos",
    "lovestory_howwemet_text": "Ambos empezamos a compartir ciudad en 2019, y una vez que Juanma comenzó a entrenar en Blankenese, empezamos a compartir instalaciones. Pachangas amistosas entre los equipos masculino y femenino llevaron a una cena de grupo en un restaurante italiano en Schanze 🍝. Fue una casualidad que ambos acabáramos allí, pero no fue casualidad que termináramos hablando toda la noche.",
    "lovestory_first_dates_title": "Primeras Citas en Pandemia",
    "lovestory_first_dates_text": "Nuestras primeras citas fueron durante la pandemia, lo que significó que tuvimos que usar la imaginación. Nuestros mejores recuerdos incluyen: Tomar una cerveza en la calle con nuestras mascarillas puestas, ir de compras juntos a nuestro supermercado gigante donde no había mucha gente, para poder pasear por los pasillos y encontrar cosas ricas para cocinar en casa, y pasear sin fin por el Volkspark con Rollo 🐕 y tener citas nocturnas en nuestros antiguos pisos.",
    "lovestory_building_life_title": "Construyendo Nuestro Mundo Juntos",
    "lovestory_building_life_text": "Todo ese tiempo condensado, lejos de las distracciones de los restaurantes de lujo, nos permitió construir algo real. Conocimos a los amigos y a la familia del otro, expandiendo nuestros círculos y nuestros corazones. Debatimos sobre nuestros gustos musicales (ligeramente compatibles 🎶) y cinematográficos (totalmente incompatibles 🎬). Jessica aprendió español y a diferenciar el jamón bueno del malo. Unos viajes a España y Dinamarca después, decidimos mudarnos juntos a nuestro apartamento tamaño caja de zapatos en Kühnehöfe. Cuando nos acostumbramos a compartir ese pequeño espacio con Rollo, dimos la bienvenida a Nuria a nuestras vidas, y ahora vivimos creando nuevos recuerdos cada día en el precioso espacio bicultural que es nuestra familia.",
    "lovestory_proposal_title": "La Pedida y la Boda Civil",
    "lovestory_proposal_text": "La decisión de casarnos comenzó, sin una pedida de mano, como un acuerdo mutuo. La parte romántica llegó como una gran sorpresa para Jessica en su cumpleaños de 2023 en el precioso Café Paris de Hamburgo. Durante un 'Desayuno para Dos' y una copa de Crémant, Juanma le propuso matrimonio y fijó la fecha de la boda civil para el 28 de noviembre de ese mismo año, el día de su cumpleaños. Así, en noviembre de 2023, nos casamos en el registro civil de Elmshorn, solo nosotros dos con Nuria y Rollo.",
    "lovestory_why_wedding_title": "¿Y por qué una Gran Celebración de Boda?",
    "lovestory_why_wedding_text": "Ahora, viviendo lejos de nuestras ciudades (Detmold y Valladolid), vemos esta celebración como nuestra mejor oportunidad para reunir a todos los que valoramos en un solo lugar. Es una ocasión para celebrar el amor, el baloncesto, nuestras culturas, la alegría, ¡y la fiesta!",
    "lovestory_gallery_title": "Algunos de Nuestros Momentos Favoritos"
});
Object.assign(translations.de, {
    "lovestory_page_title": "Unsere Geschichte",
    "lovestory_intro": "Basketball war schon immer unsere Leidenschaft. Vielleicht sind wir nicht die besten Spieler, aber das Spiel hat uns schon viel in unserem Leben gegeben: langjährige Freundschaften, emotionale Geschichten und diese Liebe. 'Love and Basketball' ist unser Motto für diesen Tag, denn durch Basketball haben wir uns kennengelernt.",
    "lovestory_howwemet_title": "Wie wir uns trafen",
    "lovestory_howwemet_text": "Es verschlug uns beide zu sehr unterschiedlichen Zeiten aus beruflichen Gründen nach Hamburg. Jessica spielte schon einige Zeit in Blankenese Basketball, als Juanma dem Airbus Team beitrat, die zur selben Zeit in der selben Halle wie Jessicas Team trainierten. Eine verspätete gemeinsame Weihnachtsfeier beider Mannschaften fand im Februar 2020 in einem italienischen Restaurant in der Schanze statt. Es war Zufall, dass wir beide dort landeten, aber es war kein Zufall, dass wir die ganze Nacht miteinander redeten.",
    "lovestory_first_dates_title": "Erste Dates während der Pandemie",
    "lovestory_first_dates_text": "Unsere ersten Verabredungen fanden während dem Beginn der Pandemie statt, was bedeutete, dass wir einfallsreich sein mussten. Unser allererstes Date fand draußen auf den Stufen eines Asia Marktes in Ottensen statt. Samstagabends unternahmen wir lange Spaziergänge im Lebensmittelgroßmarkt um die Ecke, wo wir durch jeden einzelnen Gang schlenderten um schließlich drei Zutaten für unser Abendessen zu kaufen. Mit Rolli verschlug es uns in den Volkspark und zu Abendspaziergang an die Elbe.",
    "lovestory_building_life_title": "Unsere gemeinsame Welt aufbauen",
    "lovestory_building_life_text": "Diese intensive Zeit zusammen, frei von den Ablenkungen schicker Restaurants und anderer aufregender Freizeitmöglichkeiten, erlaubte es uns, schnell etwas Echtes aufzubauen. Wir lernten Freunde und Familien des anderen kennen, erweiterten unsere Kreise und unsere Herzen. Im Oktober 2021 beschlossen wir, dass Jessica in Juanmas schuhschachtelgroße Wohnung in den Kühnehöfen einziehen sollte. Als wir uns daran gewöhnt hatten, diesen winzigen Raum mit Rollo zu teilen, begrüßten wir im Februar 2023 Nuria in unserem Leben. Seither schaffen wir jeden Tag neue Erinnerungen in unserem wunderschönen, bikulturellen Raum, der unsere Familie ist.",
    "lovestory_proposal_title": "Der Antrag und die standesamtliche Hochzeit",
    "lovestory_proposal_text": "Ganz ohne Antrag begann die Entscheidung zu heiraten für uns als gemeinsam besprochene Angelegenheit. Der romantische Teil kam für Jessica sehr überraschend an ihrem Geburtstag 2023 im wunderschönen Café Paris in Hamburg. Juanma machte ihr beim \"Frühstück für Zwei\" und einem Glas Cremant einen Heiratsantrag und fixierte das Datum der standesamtlichen Hochzeit auf den 28. November desselben Jahres - seinen Geburtstag. Im Standesamt Elmshorn heirateten wir also im November 2023 ganz unter uns mit Nuria und Rollo.",
    "lovestory_why_wedding_title": "Warum dann doch noch eine große Hochzeitsfeier?",
    "lovestory_why_wedding_text": "Da wir nun weit weg von unseren Heimatstädten Detmold und Valladolid leben, sehen wir diese Feier als unsere beste Gelegenheit, euch alle, die Menschen, die wir am meisten schätzen, an einem Ort zusammenzubringen. Es ist eine Chance, die Liebe, den Basketball, unsere Kulturen, die Freude und das Feiern zu zelebrieren!",
    "lovestory_gallery_title": "Einige unserer liebsten Momente"
});
