Object.assign(translations.en, {
    "lovestory_page_title": "Our Story",
    "lovestory_intro": "Basketball has always been our passion. We may not be the best players, but the game has given us so much in our lives: long-lasting friendships, emotional stories, and this love. \"Love and Basketball\" is our motto for this day, because it was through basketball that we met.",
    "lovestory_howwemet_title": "How We Met",
    "lovestory_howwemet_text": "For professional reasons, we both ended up in Hamburg at very different times. Jessica had been playing basketball in Blankenese for some time when Juanma joined the Airbus team, which trained at the same time and in the same gym as Jessica's team. A belated joint Christmas party for both teams took place in February 2020 at an Italian restaurant in the Schanze district. It was a coincidence that we both ended up there, but it was no coincidence that we talked to each other all night.",
    "lovestory_first_dates_title": "First Dates During the Pandemic",
    "lovestory_first_dates_text": "Our first dates took place at the beginning of the pandemic, which meant we had to be creative. Our very first date was outside on the steps of an Asian market in Ottensen. On Saturday evenings, we took long strolls through the wholesale grocery market around the corner, where we would wander down every single aisle only to eventually buy three ingredients for our dinner. With Rollo, we were drawn to the Volkspark and for evening walks along the Elbe river.",
    "lovestory_building_life_title": "Building Our World Together",
    "lovestory_building_life_text": "This intense time together, free from the distractions of fancy restaurants and other exciting leisure activities, allowed us to quickly build something real. We met each other's friends and families, expanding our circles and our hearts. In October 2021, we decided that Jessica should move into Juanma's shoebox-sized apartment in Kühnehöfe. Once we got used to sharing that tiny space with Rollo, we welcomed Nuria into our lives in February 2023. Since then, we create new memories every day in the beautiful, bicultural space that is our family.",
    "lovestory_proposal_title": "The Proposal and the Civil Ceremony",
    "lovestory_proposal_text": "The decision to marry began for us as a mutually discussed matter, without any proposal. The romantic part came as a big surprise for Jessica on her birthday in 2023 at the beautiful Café Paris in Hamburg. During a \"Breakfast for Two\" and a glass of Crémant, Juanma proposed to her and set the date for the civil ceremony to November 28th of the same year – his birthday. So, in November 2023, we got married at the Elmshorn registry office, just among ourselves with Nuria and Rollo.",
    "lovestory_why_wedding_title": "So Why a Big Wedding Celebration After All?",
    "lovestory_why_wedding_text": "Since we now live far from our hometowns of Detmold and Valladolid, we see this celebration as our best opportunity to bring all of you, the people we value most, together in one place. It's a chance to celebrate love, basketball, our cultures, joy, and to party!",
    "lovestory_gallery_title": "A Few of Our Favourite Moments"
});
Object.assign(translations.es, {
    "lovestory_page_title": "Nuestra Historia",
    "lovestory_intro": "El baloncesto siempre ha sido nuestra pasión. Quizás no seamos los mejores jugadores, pero este deporte nos ha dado mucho en la vida: amistades duraderas, historias emotivas y este amor. \"Amor y Baloncesto\" es nuestro lema para este día, porque fue a través del baloncesto como nos conocimos.",
    "lovestory_howwemet_title": "Cómo Nos Conocimos",
    "lovestory_howwemet_text": "Por motivos profesionales, ambos terminamos en Hamburgo en momentos muy diferentes. Jessica llevaba ya un tiempo jugando al baloncesto en Blankenese cuando Juanma se unió al equipo de Airbus, que entrenaba a la misma hora y en el mismo pabellón que el equipo de Jessica. Una tardía fiesta de Navidad conjunta de ambos equipos tuvo lugar en febrero de 2020 en un restaurante italiano en el barrio de Schanze. Fue una casualidad que ambos acabáramos allí, pero no fue casualidad que habláramos toda la noche.",
    "lovestory_first_dates_title": "Primeras Citas Durante la Pandemia",
    "lovestory_first_dates_text": "Nuestras primeras citas tuvieron lugar al comienzo de la pandemia, lo que significaba que teníamos que ser creativos. Nuestra primera cita fue en las escaleras de un mercado asiático en Ottensen. Los sábados por la noche, dábamos largos paseos por el supermercado mayorista de la esquina, donde recorríamos cada pasillo para finalmente comprar solo tres ingredientes para la cena. Con Rollo, nos íbamos al Volkspark y a dar paseos nocturnos por la ribera del Elba.",
    "lovestory_building_life_title": "Construyendo Nuestro Mundo Juntos",
    "lovestory_building_life_text": "Este tiempo intenso juntos, libres de las distracciones de restaurantes elegantes y otras actividades de ocio emocionantes, nos permitió construir rápidamente algo real. Conocimos a los amigos y familiares del otro, ampliando nuestros círculos y nuestros corazones. En octubre de 2021, decidimos que Jessica se mudara al apartamento tamaño caja de zapatos de Juanma en Kühnehöfe. Una vez que nos acostumbramos a compartir ese pequeño espacio con Rollo, dimos la bienvenida a Nuria a nuestras vidas en febrero de 2023. Desde entonces, creamos nuevos recuerdos cada día en el hermoso espacio bicultural que es nuestra familia.",
    "lovestory_proposal_title": "La Pedida y la Boda Civil",
    "lovestory_proposal_text": "La decisión de casarnos comenzó como un asunto discutido mutuamente, sin ninguna pedida de mano. La parte romántica llegó como una gran sorpresa para Jessica en su cumpleaños de 2023 en el precioso Café Paris de Hamburgo. Durante un \"Desayuno para Dos\" y una copa de Crémant, Juanma le pidió matrimonio y fijó la fecha de la boda civil para el 28 de noviembre de ese mismo año, el día de su cumpleaños. Así, en noviembre de 2023, nos casamos en el registro civil de Elmshorn, solo nosotros con Nuria y Rollo.",
    "lovestory_why_wedding_title": "Entonces, ¿por qué una Gran Celebración de Boda?",
    "lovestory_why_wedding_text": "Como ahora vivimos lejos de nuestras ciudades natales, Detmold y Valladolid, vemos esta celebración como nuestra mejor oportunidad para reunir a todos vosotros, las personas que más valoramos, en un solo lugar. ¡Es una oportunidad para celebrar el amor, el baloncesto, nuestras culturas, la alegría y la fiesta!",
    "lovestory_gallery_title": "Algunos de Nuestros Momentos Favoritos"
});
Object.assign(translations.de, {
    "lovestory_page_title": "Unsere Geschichte",
    "lovestory_intro": "Basketball war schon immer unsere Leidenschaft. Vielleicht sind wir nicht die besten Spieler, aber das Spiel hat uns schon viel in unserem Leben gegeben: langjährige Freundschaften, emotionale Geschichten und diese Liebe. \"Love and Basketball\" ist unser Motto für diesen Tag, denn durch Basketball haben wir uns kennengelernt.",
    "lovestory_howwemet_title": "Wie wir uns trafen",
    "lovestory_howwemet_text": "Es verschlug uns beide zu sehr unterschiedlichen Zeiten aus beruflichen Gründen nach Hamburg. Jessica spielte schon einige Zeit in Blankenese Basketball, als Juanma dem Airbus Team beitrat, die zur selben Zeit in der selben Halle wie Jessicas Team trainierten. Eine verspätete gemeinsame Weihnachtsfeier beider Mannschaften fand im Februar 2020 in einem italienischen Restaurant in der Schanze statt. Es war Zufall, dass wir beide dort landeten, aber es war kein Zufall, dass wir die ganze Nacht miteinander redeten.",
    "lovestory_first_dates_title": "Erste Dates während der Pandemie",
    "lovestory_first_dates_text": "Unsere ersten Verabredungen fanden während dem Beginn der Pandemie statt, was bedeutete, dass wir einfallsreich sein mussten. Unser allererstes Date fand draußen auf den Stufen eines Asia Marktes in Ottensen. Samstagabends unternahmen wir lange Spaziergänge im Lebensmittelgroßmarkt um die Ecke, wo wir durch jeden einzelnen Gang schlenderten um schließlich drei Zutaten für unser Abendessen zu kaufen. Mit Rolli verschlug es uns in den Volkspark und zu Abendspaziergang an die Elbe.",
    "lovestory_building_life_title": "Unsere gemeinsame Welt aufbauen",
    "lovestory_building_life_text": "Diese intensive Zeit zusammen, frei von den Ablenkungen schicker Restaurants und anderer aufregender Freizeitmöglichkeiten, erlaubte es uns, schnell etwas Echtes aufzubauen. Wir lernten Freunde und Familien des anderen kennen, erweiterten unsere Kreise und unsere Herzen. Im Oktober 2021 beschlossen wir, dass Jessica in Juanmas schuhschachtelgroße Wohnung in den Kühnehöfen einziehen sollte. Als wir uns daran gewöhnt hatten, diesen winzigen Raum mit Rollo zu teilen, begrüßten wir im Februar 2023 Nuria in unserem Leben. Seither schaffen wir jeden Tag neue Erinnerungen in unserem wunderschönen, bikulturellen Raum, der unsere Familie ist.",
    "lovestory_proposal_title": "Der Antrag und die standesamtliche Hochzeit",
    "lovestory_proposal_text": "Ganz ohne Antrag begann die Entscheidung zu heiraten für uns als gemeinsam besprochene Angelegenheit. Der romantische Teil kam für Jessica sehr überraschend an ihrem Geburtstag 2023 im wunderschönen Café Paris in Hamburg. Juanma machte ihr beim \"Frühstück für Zwei\" und einem Glas Cremant einen Heiratsantrag und fixierte das Datum der standesamtlichen Hochzeit auf den 28. November desselben Jahres - seinen Geburtstag. Im Standesamt Elmshorn heirateten wir also im November 2023 ganz unter uns mit Nuria und Rollo.",
    "lovestory_why_wedding_title": "Warum dann doch noch eine große Hochzeitsfeier?",
    "lovestory_why_wedding_text": "Da wir nun weit weg von unseren Heimatstädten Detmold und Valladolid leben, sehen wir diese Feier als unsere beste Gelegenheit, euch alle, die Menschen, die wir am meisten schätzen, an einem Ort zusammenzubringen. Es ist eine Chance, die Liebe, den Basketball, unsere Kulturen, die Freude und das Feiern zu zelebrieren!",
    "lovestory_gallery_title": "Einige unserer liebsten Momente"
});