Object.assign(translations.en, {
    "rec_region_title": "The Region",
    "section_title_region": "Our Corner of Spain",
    "recommendations_region_intro": "Welcome to Castile and León. This region is the historic heartland of Spain, situated on the vast, high plateau known as the <em>Meseta Central</em>. It's where the Spanish language was formed and the unification of the country began—a land of stark horizons, profound history, and many, many castles.",
    "recommendations_region_text": "<strong>Recommended winery visit:</strong> Yllera ({{LINK_YLLERA}}) – striking architecture, restaurant and hotel.<br><strong>More bodegas:</strong> Arzuaga ({{LINK_ARZUAGA}}), Protos, Peñafiel.<br><strong>Traditional food in old bodegas:</strong> Bodega la Sorbona near Valladolid ({{LINK_BODEGA_SORBONA}}).<br><strong>Castles:</strong> Peñafiel, Tiedra, Íscar.<br><strong>Cities:</strong> Segovia, León, Burgos, Ávila, Salamanca",
    "section_title_castles": "Notable Castles",
    "castles_intro": "The province is known for its many castles—stern fortresses that served as royal residences, state prisons, and strategic outposts. A short drive from the city can take you to some truly impressive historical sites.",
    "castle_simancas": "<strong>Simancas Castle (Approx. 20 min drive):</strong> This was more than a fortress; it was the memory of an empire. King Philip II converted it into the General Archive of the Kingdom, one of the most important historical archives in the world, holding millions of documents. You can book a tour to see where Spain's history was kept.",
    "castle_portillo": "<strong>Portillo Castle (Approx. 30 min drive):</strong> A classic example of the \"School of Valladolid\" castle-palace style. It has a deep moat carved from the limestone bedrock and also served as a state prison. Its most famous prisoner was Don Álvaro de Luna, a powerful political figure who was held here before his execution.",
    "castle_mota": "<strong>La Mota Castle (Approx. 45 min drive):</strong> Located in Medina del Campo, this is a formidable 15th-century fortress that served as a high-security state prison. Its most famous inmate was Cesare Borgia, who made a legendary escape from its 40-meter-high keep.",
    "castle_penafiel": "<strong>Peñafiel Castle (Approx. 50 min drive):</strong> A personal favorite. Its unique ship-like shape sits atop a hill offering fantastic views. Legend says it was named \"the faithful rock of Castile\" after being captured from the Moors in 1013. It now houses the Provincial Wine Museum.",
    "castle_arevalo": "<strong>Arévalo Castle (Approx. 1 hr drive):</strong> Also known as the Castle of the Zúñiga, this 15th-century fortress is a beautiful example of Mudejar-style military architecture, with its distinctive pentagonal keep. It has a rich history, having served as a royal residence for figures like Isabella I of Castile."
});

Object.assign(translations.es, {
    "rec_region_title": "La Región",
    "section_title_region": "Nuestro Rincón de España",
    "recommendations_region_intro": "Bienvenidos a Castilla y León. Esta región es el corazón histórico de España, situada en la vasta meseta norte. Es donde se formó el idioma español y comenzó la unificación del país; una tierra de horizontes austeros, profunda historia y muchísimos castillos.",
    "recommendations_region_text": "<strong>Bodega recomendada para visitar:</strong> Yllera ({{LINK_YLLERA}}): arquitectura llamativa, restaurante y hotel.<br><strong>Más bodegas:</strong> Arzuaga ({{LINK_ARZUAGA}}), Protos, Peñafiel.<br><strong>Comer en bodegas tradicionales:</strong> Bodega la Sorbona cerca de Valladolid ({{LINK_BODEGA_SORBONA}}).<br><strong>Castillos:</strong> Peñafiel, Tiedra, Íscar.<br><strong>Ciudades:</strong> Segovia, León, Burgos, Ávila, Salamanca",
    "section_title_castles": "Castillos Notables",
    "castles_intro": "La provincia es conocida por sus muchos castillos: severas fortalezas que sirvieron como residencias reales, prisiones de estado y puestos estratégicos. Un corto trayecto en coche desde la ciudad puede llevaros a sitios históricos realmente impresionantes.",
    "castle_simancas": "<strong>Castillo de Simancas (Aprox. 20 min en coche):</strong> Esto fue más que una fortaleza; fue la memoria de un imperio. El rey Felipe II lo convirtió en el Archivo General del Reino, uno de los archivos históricos más importantes del mundo, con millones de documentos. Se puede reservar una visita para ver dónde se guardaba la historia de España.",
    "castle_portillo": "<strong>Castillo de Portillo (Aprox. 30 min en coche):</strong> Un ejemplo clásico del estilo castillo-palacio de la \"Escuela de Valladolid\". Tiene un profundo foso excavado en la roca caliza y también sirvió como prisión de estado. Su prisionero más famoso fue Don Álvaro de Luna, una poderosa figura política que estuvo aquí antes de su ejecución.",
    "castle_mota": "<strong>Castillo de La Mota (Aprox. 45 min en coche):</strong> Situado en Medina del Campo, esta es una formidable fortaleza del siglo XV que sirvió como prisión de estado de alta seguridad. Su prisionero más famoso fue César Borgia, que protagonizó una legendaria fuga desde su torre del homenaje de 40 metros de altura.",
    "castle_penafiel": "<strong>Castillo de Peñafiel (Aprox. 50 min en coche):</strong> Un favorito personal. Su singular forma de barco se asienta en lo alto de una colina ofreciendo vistas fantásticas. La leyenda dice que fue nombrada \"la peña fiel de Castilla\" tras ser reconquistada en 1013. Ahora alberga el Museo Provincial del Vino.",
    "castle_arevalo": "<strong>Castillo de Arévalo (Aprox. 1 h en coche):</strong> También conocido como el Castillo de los Zúñiga, esta fortaleza del siglo XV es un bello ejemplo de arquitectura militar de estilo mudéjar, con su característica torre del homenaje pentagonal. Tiene una rica historia, habiendo servido como residencia real para figuras como Isabel I de Castilla."
});

Object.assign(translations.de, {
    "rec_region_title": "Die Region",
    "section_title_region": "Unsere Ecke von Spanien",
    "recommendations_region_intro": "Willkommen in Kastilien und León. Diese Region ist das historische Kernland Spaniens, gelegen auf dem weiten, kastilischen Hochland (<em>Meseta Central</em>). Hier wurde die spanische Sprache geformt und die Vereinigung des Landes begann – ein Land der weiten Horizonte, tiefgreifender Geschichte und sehr, sehr vieler Burgen.",
    "recommendations_region_text": "<strong>Empfohlene Bodega:</strong> Yllera ({{LINK_YLLERA}}) – moderne Architektur, Restaurant und Hotel.<br><strong>Weitere Bodegas:</strong> Arzuaga ({{LINK_ARZUAGA}}), Protos, Peñafiel.<br><strong>Traditionell essen in alten Bodegas:</strong> Bodega la Sorbona bei Valladolid ({{LINK_BODEGA_SORBONA}}).<br><strong>Castillos:</strong> Peñafiel, Tiedra, Íscar.<br><strong>Städte:</strong> Segovia, León, Burgos, Ávila, Salamanca",
    "section_title_castles": "Bemerkenswerte Burgen",
    "castles_intro": "Die Provinz ist für ihre vielen Burgen bekannt – strenge Festungen, die als königliche Residenzen, Staatsgefängnisse und strategische Außenposten dienten. Eine kurze Autofahrt von der Stadt entfernt können Sie einige wirklich beeindruckende historische Stätten besichtigen.",
    "castle_simancas": "<strong>Burg Simancas (ca. 20 Min. Fahrt):</strong> Dies war mehr als eine Festung; es war das Gedächtnis eines Reiches. König Philipp II. wandelte es in das Generalarchiv des Königreichs um, eines der wichtigsten historischen Archive der Welt, das Millionen von Dokumenten enthält. Man kann eine Führung buchen, um zu sehen, wo die Geschichte Spaniens aufbewahrt wurde.",
    "castle_portillo": "<strong>Burg Portillo (ca. 30 Min. Fahrt):</strong> Ein klassisches Beispiel für den Schloss-Palast-Stil der \"Schule von Valladolid\". Sie hat einen tiefen, aus dem Kalksteinfelsen gehauenen Graben und diente ebenfalls als Staatsgefängnis. Ihr berühmtester Gefangener war Don Álvaro de Luna, eine mächtige politische Figur, die hier vor ihrer Hinrichtung festgehalten wurde.",
    "castle_mota": "<strong>Burg La Mota (ca. 45 Min. Fahrt):</strong> In Medina del Campo gelegen, ist dies eine gewaltige Festung aus dem 15. Jahrhundert, die als Hochsicherheits-Staatsgefängnis diente. Ihr berühmtester Insasse war Cesare Borgia, dem eine legendäre Flucht aus ihrem 40 Meter hohen Bergfried gelang.",
    "castle_penafiel": "<strong>Burg Peñafiel (ca. 50 Min. Fahrt):</strong> Ein persönlicher Favorit. Ihre einzigartige schiffsähnliche Form thront auf einem Hügel und bietet eine fantastische Aussicht. Die Legende besagt, dass sie nach der Eroberung von den Mauren im Jahr 1013 \"der treue Fels Kastiliens\" genannt wurde. Sie beherbergt heute das Provinz-Weinmuseum.",
    "castle_arevalo": "<strong>Burg Arévalo (ca. 1 Std. Fahrt):</strong> Auch bekannt als das Schloss der Zúñiga, ist diese Festung aus dem 15. Jahrhundert ein wunderschönes Beispiel für Militärarchitektur im Mudejar-Stil, mit ihrem charakteristischen fünfeckigen Bergfried. Sie hat eine reiche Geschichte und diente als königliche Residenz für Persönlichkeiten wie Isabella I. von Kastilien."
});